[project]
name = "ticker-screener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv==1.0.1",
    "python-telegram-bot[job-queue]==21.10",
    "yfinance==0.2.65",
]
